version: '3.7'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: nuxt-docker-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    expose:
      - "3000"
    environment:
      - VIRTUAL_HOST=user156.com
      - VIRTUAL_PORT=3000

networks:
  default:
    external:
      name: nginx-proxy